### ISSUE TITLE
Towards robust RTSS

### ISSUE THREAD

**Issue by devanshdhrafani** [castacks/wildfire-zenhub#335]
Deadline: 11/15/23

**Comment by MsFriendly** [comment]
[Test Result Table](https://docs.google.com/document/d/12jcntDjtv1mUQm8kwFtJtKT1OfjQGYTiB0oCTJZ7JWM/edit?usp=sharing) with gradual data check and function-by-function debug. Will switch to 3 camera setup after discussion
